### ISSUE TITLE
总是出现这个错误，是什么原因。

### ISSUE THREAD

**Issue by poikl369** [ctiao/DanmakuFlameMaster#62]
01-13 16:55:13.663: W/System.err(27536): java.lang.IllegalArgumentException: master.flame.danmaku.danmaku.model.R2LDanmaku@4364e440 not in range [master.flame.danmaku.danmaku.model.Danmaku@43608568..master.flame.danmaku.danmaku.model.Danmaku@436085e0)
at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:440)

**Comment by ctiao** [comment]
使用最新的代码  @poikl369

**Comment by poikl369** [comment]
还有一个问题就是，弹幕多的时候会影响到视频，导致视频一卡一卡的，我估计是占用了太多的CPU，而且视频的解码是软解码的，CPU的负荷太大了，解码不过来。

**Comment by ctiao** [comment]
这个暂时没有好的解决办法，要么视频尽量使用硬解，要么弹幕绘制部分实现硬件加速，还有就是代码优化降低CPU使用率
