### ISSUE TITLE
一个duration的问题

### ISSUE THREAD

**Issue by jianghao1123** [ctiao/DanmakuFlameMaster#63]
给弹幕设置duration，当一大波弹幕发出来后，有些弹幕走到半路忽然消失，不设置duration正常

**Comment by ctiao** [comment]
滚动弹幕的duration都是统一的，一是由于滚动弹幕本来就是这么设计(在固定时间内跑完)，二是为了可以控制全局速率

**Comment by jianghao1123** [comment]
thanks，请问我如何去控制全局速率呢？

**Comment by ctiao** [comment]
DanmakuGlobalConfig.DEFAULT.setXXXXX  系列方法控制弹幕的设置
看DanmakuGlobalConfig.java里的注释
