### ISSUE TITLE
R2LDanmaku 类中 mTimer.currMillisecond 变化的位置？

### ISSUE THREAD

**Issue by langzuxiaozi** [ctiao/DanmakuFlameMaster#65]
我在R2LDanmaku类的getAccurateLeft方法中打印 currTime 参数日志。

01-28 18:23:11.070: E/danmubbc(13522): currTime = 11589 time =6079 displayer.getWidth() = 1920 elapsedTime = 5510 duration.value = 5630 mStepX=0.37531084
01-28 18:23:11.071: E/danmubbc(13522): 2text = 陈佩斯 left = -147.96265
01-28 18:23:11.096: E/danmubbc(13522): 1text = 陈佩斯 left = -147.96265
01-28 18:23:11.097: E/danmubbc(13522): currTime = 11642 time =6079 displayer.getWidth() = 1920 elapsedTime = 5563 duration.value = 5630 mStepX=0.37531084
01-28 18:23:11.097: E/danmubbc(13522): 2text = 陈佩斯 left = -167.85425
01-28 18:23:11.103: E/danmubbc(13522): 1text = 陈佩斯 left = -167.85425
01-28 18:23:11.103: E/danmubbc(13522): currTime = 11695 time =6079 displayer.getWidth() = 1920 elapsedTime = 5616 duration.value = 5630 mStepX=0.37531084
01-28 18:23:11.103: E/danmubbc(13522): 2text = 陈佩斯 left = -187.7456
01-28 18:23:11.139: E/danmubbc(13522): 1text = 陈佩斯 left = -187.7456
01-28 18:23:11.139: E/danmubbc(13522): 2text = 陈佩斯 left = -187.7456
01-28 18:23:11.162: E/danmubbc(13522): 1text = 陈佩斯 left = -187.7456
01-28 18:23:11.163: E/danmubbc(13522): currTime = 9856time =6079 displayer.getWidth() = 1920 elapsedTime = 3777 duration.value = 5630 mStepX=0.37531084
01-28 18:23:11.163: E/danmubbc(13522): 2text = 陈佩斯 left = 502.45093
01-28 18:23:11.171: E/danmubbc(13522): 1text = 陈佩斯 left = 502.45093

正常情况下是currTime不断的变大，但是有时会出现currTime突然变小，然后在慢慢变大的情况。

导致的现象就是，弹幕从右到左走完后，突然又从中间显示，再向左走的情况。

currTime 的值来自mTimer.currMillisecond。所以我想知道currMillisecond是根据什么变化的，在代码的什么位置变化？

**Comment by ctiao** [comment]
正在修这个问题，  为了弹幕滚动稳定加了很多更新timer的操作  导致currTime出现问题

**Comment by ctiao** [comment]
可以将DrawHandler.java里的  mUpdateInNewThread = (Runtime.getRuntime().availableProcessors() > 3);  这句去掉试试

**Comment by ctiao** [comment]
06f55567d89941c713ca28d26b852a614a7d38b3

**Comment by langzuxiaozi** [comment]
我看修改的是线程的代码.
我注释掉线程还是会出现问题呀
// mUpdateInNewThread = (Runtime.getRuntime().availableProcessors() > 3);
 mUpdateInNewThread ＝ false

**Comment by ctiao** [comment]
使用的是最新的代码吗
