### ISSUE TITLE
DanmakuTextureView seek后会有弹幕加速问题

### ISSUE THREAD

**Issue by ctiao** [ctiao/DanmakuFlameMaster#66]
DanmakuSurfaceView无此问题，   应该是DrawHandler调整timer的更新出了问题

**Comment by kmfish** [comment]
In DrawHandler.java:
原因：线程退出的判断条件 isInterrupted(), 会在thread 抛出InterruptedException 后重新置为false，而这个while 里的代码可能会抛出该exception（waitRendering里 wait），之前的代码在内部捕获了该异常，然后代码继续往下走，进行下一次循环判断， 此时 isInterrupted() == false了，所以线程并未退出，导致了该bug。

**Comment by ctiao** [comment]
谢谢，我修改下

**Comment by ctiao** [comment]
https://github.com/ctiao/DanmakuFlameMaster/commit/06f55567d89941c713ca28d26b852a614a7d38b3
已修复

**Comment by yrom** [comment]
ctiao/DanmakuFlameMaster#65
