### ISSUE TITLE
请教一个弹幕release的问题

### ISSUE THREAD

**Issue by xiaojianan** [ctiao/DanmakuFlameMaster#67]
我在fragment中使用弹幕，但是当我销毁fragment后发现弹幕数据的jsonArray并没有被回收掉，导致弹幕数据对象依旧占用内存，即使退出应用也是如此，所以我在JsonSource中 release时将mJsonArray置为null，经测试，发现已经可以正常回收，想请教下这样会有什么问题吗，感谢。
JsonSource:
@Override
    public void release() {
        IOUtils.closeQuietly(mInput);
        mInput = null;
        //回收mJSONArray
        mJSONArray = null;
    }

**Comment by ctiao** [comment]
这样改没有问题。
不过有点奇怪如果JsonSource的实例被回收，他的成员应该也会被回收的,JsonSource在BaseDanmakuParser里的parse()之后已经release并且置null, 为什么mJSONArray没有被一起回收呢

**Comment by yrom** [comment]
你是如何得知“jsonArray并没有被回收掉”

**Comment by xiaojianan** [comment]
当我的视频播放的fragment被remove后，查看内存，发现弹幕的相应数据还存在内存中，弹幕的release方法有调用，具体的还没有分析清楚，但看起来像是DanmakuLoader在持有mJsonArray的引用：
![7d801a3a-959f-40e8-a643-10da08ffae05](https://cloud.githubusercontent.com/assets/7122983/6100278/8c3324e8-b047-11e4-9fca-1ecd183d9b08.png)

**Comment by xiaojianan** [comment]
请帮忙看下是不是这样，AcFunDanmakuLoader的instance持有JSONSource dataSource对象，dataSource持有JSONSource对象，在JSONSource中，release后，mJSONArray并没有被回收，而AcFunDanmakuLoader的instance对象不会被回收，最终导致了mJSONArray不能被回收。

**Comment by xiaojianan** [comment]
![ef65de91-146a-4814-8939-b0062b377593](https://cloud.githubusercontent.com/assets/7122983/6100593/75b0fcee-b04d-11e4-86ad-fd339c471499.png)
补一张我在release中将mJsonArray置为null后的内存，可以看见，AcFunDanmakuLoader依旧存在内存中，但是mJsonArray因为已经被回收，所以AcFunDanmakuLoader对象已经不占用内存。我怀疑跟fragment有关，如果是activity中应该不存在此问题。

**Comment by yrom** [comment]
应该是静态变量instance的问题

**Comment by ctiao** [comment]
提交个pull request 吧
