### ISSUE TITLE
DanmakuTextureView 在很多机子上面报错

### ISSUE THREAD

**Issue by poikl369** [ctiao/DanmakuFlameMaster#69]
DanmakuSurfaceView 跟我自己做的播放器的SurfaceView 有冲突 。

**Comment by ctiao** [comment]
报什么错？
TextureView只能在android 4.0+(api >= 14) 的系统上运行
SurfaceView确实限制多多,我正在增加一个通过普通View实现的弹幕绘制方式

**Comment by ctiao** [comment]
跟你的播放器SurfaceView有冲突是指什么？

**Comment by poikl369** [comment]
我开始用的DanmakuSurfaceView 和我自己的SurfaceView直接有冲突，但是有时可以显示出来，有时不能显示。应该是SurfaceView和SurfaceView的层级会有混乱，DanmakuTextureView在和你多机型上面爆了找不到方法。就是在你调用动态库里面的一个方法.

**Comment by ctiao** [comment]
SurfaceView的层级可以通过 setZOrderMediaOverlay或setZOrderOnTop方法指定，两个方法各有优缺点，两个SurfaceView的层级也跟Layout的层级有关
DanmakuTextureView爆找不到方法具体是哪个方法  ？  有log吗 系统版本是多少？

**Comment by ctiao** [comment]
https://github.com/ctiao/DanmakuFlameMaster/tree/dev-view-canvas

这个分支实现一个扩展普通View的DanmakuView,请帮忙测试下

**Comment by poikl369** [comment]
我试试看吧.
