### ISSUE TITLE
我还有一个问题，现在弹幕的显示位置是根据时间来的，我现在的需求是每个弹幕不能重叠，如果并发同时添加100个弹幕，我该怎么处理好。

### ISSUE THREAD

**Issue by DukeLee1989** [ctiao/DanmakuFlameMaster#71]

**Comment by ctiao** [comment]
首选要知道一屏最多几行弹幕，发送第一批x条弹幕(x=行数)  
当前弹幕时间 + 一定增量时间，用DanmakuUtils.willHitInDuration检查第一行弹幕与当前要插入弹幕是否会碰撞，会碰撞则再增加一定时间再检查，不会碰撞则确定当前弹幕出现的time，如此循环直到插完第二批x条弹幕(x=行数)
后面剩余的弹幕同样处理。

**Comment by DukeLee1989** [comment]
嗯，谢谢了，有问题再来请教您。

**Comment by ctiao** [comment]
https://github.com/Bilibili/DanmakuFlameMaster/commit/5ab69f6995c9d0766cccaea660603852b9a3f6ed

增加了控制行数和防重叠功能
