### ISSUE TITLE
iOS上如何实现弹幕效果呢？

### ISSUE THREAD

**Issue by chenweiyj** [ctiao/DanmakuFlameMaster#72]

**Comment by jordankan** [comment]
IOS直接动画上

**Comment by CrazyPeter** [comment]
iOS弹幕动画是大量的Label+UIviewAnimation
or
CoreText+CALayer动画？

**Comment by unash** [comment]
最近写了一个开源的iOS弹幕引擎：https://github.com/unash/BarrageRenderer。可以试试。
