### ISSUE TITLE
如何监听当前所有弹幕加载完毕?

### ISSUE THREAD

**Issue by JollyJiang** [ctiao/DanmakuFlameMaster#74]
如题,需要加载完毕后重新播放,或者去更新弹幕数据.

**Comment by ctiao** [comment]
danmakuview.setCallback(
Callback回调里有个prepared事件

**Comment by JollyJiang** [comment]
可能我标题有歧义,我的意思是,所有弹幕显示完,有没有回调?我想让弹幕循环显示,但是#45 里面没明白seek(0)具体在哪使用.

**Comment by ctiao** [comment]
一般是视频播放完重播时seek(0)
你的需求是没有视频时间同步的情况下独立显示弹幕，暂时没有提供播放完弹幕这个回调 
自己修改的话参考这个commit  https://github.com/ctiao/DanmakuFlameMaster/commit/90b0c97174f9fc5c926c9ee53135c6f861460ca1
未经测试 仅供参考

**Comment by JollyJiang** [comment]
多谢.试了下可以了
