### ISSUE TITLE
新手请教，导入该项目，报错问题

### ISSUE THREAD

**Issue by zengcheng888** [ctiao/DanmakuFlameMaster#78]
导入完成后，eclipse里面多了两个工程DanmakuFlameMaster和Sample。
DanmakuFlameMaster提示：DanmakuFlameMaster\src\main\res' does not exist
Sample项目前面有感叹号
请问该如何处理，盼前辈们答复

**Comment by ctiao** [comment]
在项目里建一个空的res目录  如果还有其他目录提示，同样操作

**Comment by zengcheng888** [comment]
OK了，谢谢啊。
