### ISSUE TITLE
使用BaseDanmaku.TYPE_SPECIAL报空指针

### ISSUE THREAD

**Issue by zengcheng888** [ctiao/DanmakuFlameMaster#79]
您好，由于项目需要，想通过Sample里的addDanmaku（）方法实现添加位置随机的弹幕。
例子中使用的是TYPE_SCROLL_RL，这种效果使得弹幕是从上到下排列的，位置没有随机。
本以为BaseDanmaku.TYPE_SPECIAL能满足需求，结果报空指针错误了，另外，TYPE_MOVEABLE_XXX也是报空指针。
求教以上是什么原因，以及如何能较方便的实现弹幕位置随机。

**Comment by xqq** [comment]
崩溃时具体log? 调用栈信息?
实现弹幕位置随机，参考 BiliDanmukuParser
https://github.com/ctiao/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/parser/android/BiliDanmukuParser.java

**Comment by ctiao** [comment]
https://github.com/ctiao/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/parser/android/BiliDanmukuParser.java#L203-L208
https://github.com/ctiao/DanmakuFlameMaster/blob/master/DanmakuFlameMaster/src/main/java/master/flame/danmaku/danmaku/parser/DanmakuFactory.java#L247-L296

TYPE_SPECIAL类型的弹幕需要按需求设置几个属性(独立存活时间、坐标变化、透明度变化、运动路径等...) 才能生效 ，目前支持B站的特殊弹幕属性如下
![image](https://cloud.githubusercontent.com/assets/3433776/6817692/30edfd6e-d2df-11e4-9009-0119fdd35533.png)

**Comment by zengcheng888** [comment]
非常感谢。可不可以在comment文件里面加入一些特殊弹幕的配置，方便我们学习~~~

**Comment by ctiao** [comment]
可以去B站找找一些神弹幕，不知道网上有没有人整理这些。
