### ISSUE TITLE
暂停弹幕状态下改变弹幕控件的大小时弹幕内容不显示

### ISSUE THREAD

**Issue by hllai** [ctiao/DanmakuFlameMaster#80]
在暂停弹幕状态下，改变弹幕控件的大小时弹幕内容消失不见，恢复播放状态下弹幕内容会从原位置开始播放。而在播放状态下，改变弹幕控件的大小时弹幕内容就不会消失。
不管弹幕控件是使用DanmakuSurfaceView还是DanmakuView

改变方式：
private void changeDanmakuView( RelativeLayout view )
{
   if （ null ==  mDanmakuView ）
  {
    mDanmakuView = new DanmakuSurfaceView( mContext );
  }
  if ( null != mLastRootView )
 {
    mLastRootView.removeView( mDanmakuView );
 }
  RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams( 
  	RelativeLayout.LayoutParams.MATCH_PARENT, 80 );
  view .addView( mDanmakuView, params );
mLastRootView = view;
}
由于横屏和竖屏各自独立，所以有两个view，但是弹幕控件只有一个，为了做到横竖屏都能用，所以弹幕控件直接new出来的，view 的宽度都是MATCH_PARENT，高度限制为500，横竖屏切换过程中传入不同状态下的View来变换弹幕控件显示

**Comment by xqq** [comment]
是最新的代码么？
无法复现。改变DanmakuView后弹幕正常显示，没有消失。
请提供完整的可重现demo代码

**Comment by hllai** [comment]
今天重新更新最新的代码，已经没有问题了，谢谢了。
