### ISSUE TITLE
使用弹幕的activity被后来的activity遮盖完全不可见，再次可见时弹幕就不出现了

### ISSUE THREAD

**Issue by zengcheng888** [ctiao/DanmakuFlameMaster#82]
您好，我的代码仿照例子写的，在activity的生命周期内加入了对danmukuView的操作。目前发现，一旦使用弹幕的activity进入后台，再从后台到可见状态，弹幕就出不来了，activity的onPause方法中加入了danmukuView.pause，activity的onResume中也加入了danmukuView.resume。照着例子写的，是不是在onStop里面还有做什么操作啊？

**Comment by ctiao** [comment]
是什么原因？
