### ISSUE TITLE
使用DanmakuView当弹幕hide时调用mDanmakuView.resume和pause，屏幕会重新绘制出当前处于停止状态的danmaku文字

### ISSUE THREAD

**Issue by xiaojianan** [ctiao/DanmakuFlameMaster#83]
当对DanmakuView调用hide之后，再调用resume或pause方法，屏幕上会重新绘制出文字，此时的文字在屏幕上处于停止状态，正确的是屏幕上不应该绘制出文字，此错误在使用DanmakuView存在，DanmakuSurfaceView不存在此问题，DanmakuTextureView未验证。

个人猜测解决方案：在DrawHandler中的notifyRendering()方法中加入判断：
    if (!mDanmakusVisible)  {
            return;
    }
已验证DanmakuView中不会再出现此问题，未验证是否会对DanmakuSurfaceView及DanmakuTextureView是否产生影响，其他影响未知，请帮忙分析，非常感谢。

PS:不知道这个错误是否只在我手机上产生。

**Comment by xqq** [comment]
已在master上修复，请更新代码
