### ISSUE TITLE
亲，今天同步更新了你们的代码后又复现了之前的一个bug

### ISSUE THREAD

**Issue by hllai** [ctiao/DanmakuFlameMaster#84]
使用你们的demo，点击暂停弹幕，然后旋转屏幕，弹幕内容消失。不会恢复后就马上能看见了，

这个问题在之前我反馈过，不过在更新你们最新代码后就好了。具体请看第#82个问题

**Comment by xqq** [comment]
收到，已重现

**Comment by hllai** [comment]
更新了最新代码（Commits on Apr 4, 2015），已解决！
